Repository exonum/exonum-java-binding, pull requests merged in 2018-07, with the labels that each got.

#319 Reenable clippy on travis [ECR-1538].
  .travis.yml
  exonum-java-binding-core/rust/ejb-app/src/main.rs
  exonum-java-binding-core/rust/integration_tests/src/mock/service.rs
  exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
  exonum-java-binding-core/rust/integration_tests/tests/dumb_executor.rs
  exonum-java-binding-core/rust/integration_tests/tests/hacky_executor.rs
  exonum-java-binding-core/rust/integration_tests/tests/node_context.rs
  exonum-java-binding-core/rust/integration_tests/tests/service_proxy.rs
  exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
  exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
  exonum-java-binding-core/rust/src/proxy/node.rs
  exonum-java-binding-core/rust/src/proxy/service.rs
  exonum-java-binding-core/rust/src/proxy/transaction.rs
  exonum-java-binding-core/rust/src/runtime/cmd.rs
  exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
  exonum-java-binding-core/rust/src/storage/proof_map_index.rs
  exonum-java-binding-core/rust/src/utils/conversion.rs
  exonum-java-binding-core/rust/src/utils/mod.rs
  exonum-java-binding-core/rust/src/utils/resource_manager/imp.rs
Labels: work-in-progress :construction_worker_man:

#335 update script for creating cryptocurrency node
  exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
Labels: Next to merge :flight_arrival:

#340 Prepend /api before the path to the API of a service.
  exonum-java-binding-core/src/main/java/com/exonum/binding/service/adapters/UserServiceAdapter.java
  exonum-java-binding-core/src/test/java/com/exonum/binding/service/adapters/UserServiceAdapterTest.java
Labels: enhancement :rocket:

#330 Add native support for flat proofs [ECR-1350]
  exonum-java-binding-core/rust/src/storage/proof_map_index.rs
Labels: Next to merge :flight_arrival:

#306 ECR-1708 Change configuration in deploy plugins and add a badge
  README.md
  exonum-java-binding-core/pom.xml
  exonum-java-binding-cryptocurrency-demo/pom.xml
  exonum-java-binding-fakes/pom.xml
  exonum-java-binding-qa-service/pom.xml
  exonum-java-binding-service-archetype/pom.xml
  exonum-java-proofs/pom.xml
  exonum-java-testing/pom.xml
  pom.xml
Labels: Next to merge :flight_arrival:

#338 Add list of services to enable (ECR-1766) & bundle btc-anchoring (ECR-1366)
  exonum-java-binding-core/rust/ejb-app/Cargo.toml
  exonum-java-binding-core/rust/ejb-app/src/main.rs
  exonum-java-binding-core/rust/ejb-app/src/node_builder.rs
  run_all_tests.sh
  run_ejb_app_tests.sh
Labels: Next to merge :flight_arrival:

#354 Fix build status badge in README
  README.md
Labels: work-in-progress :construction_worker_man:

#355 ECR-889 Add StandardSerializers roundtrip test
  exonum-java-proofs/src/test/java/com/exonum/binding/storage/serialization/StandardSerializersRoundtripTest.java
Labels: Next to merge :flight_arrival:

#359 Fix start_qa_node script after adding JVM arguments.
  exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
Labels: Next to merge :flight_arrival:

#349 Rollback Rust compiler version [ECR-1853]
  .travis.yml
  CONTRIBUTING.md
  ROADMAP.md
  exonum-java-binding-core/pom.xml
  exonum-java-binding-core/rust/ejb-app/TUTORIAL.md
  exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
  exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
  run_all_tests.sh
  run_ejb_app_tests.sh
  run_native_integration_tests.sh
Labels: Next to merge :flight_arrival:

#356 Add CHANGELOG.md [ECR-1517]
  CHANGELOG.md
Labels: Next to merge :flight_arrival:

#378 Skip CI if only markdown files were updated.
  .travis.yml
  skip-ci.sh
Labels: Next to merge :flight_arrival:

#323 Skip Java integration tests on Linux only [ECR-1742]:
  exonum-java-binding-core/pom.xml
  exonum-java-binding-cryptocurrency-demo/pom.xml
  exonum-java-binding-fakes/pom.xml
  exonum-java-binding-qa-service/pom.xml
  pom.xml
Labels: Next to merge :flight_arrival:
