Repository exonum/exonum-java-binding, pull requests merged in 2018-09, with the labels that each got.

#467 [ECR-1920] Move `crypto` package to `common` module
  exonum-java-binding-common/pom.xml
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/AbstractKey.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/CryptoFunction.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/CryptoFunctions.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/CryptoUtils.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/Ed25519CryptoFunction.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/KeyPair.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/PrivateKey.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/PublicKey.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/crypto/PublicKeySerializer.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/crypto/AbstractKeyTest.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/crypto/CryptoUtilsTest.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/crypto/Ed25519CryptoFunctionTest.java
  exonum-java-binding-core/pom.xml
Labels: java

#476 Fix rustfmt
  exonum-java-binding-core/rust/integration_tests/src/executor.rs
  exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
  exonum-java-binding-core/rust/integration_tests/src/test_service.rs
  exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
  exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
  exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
  exonum-java-binding-core/rust/src/proxy/service.rs
  exonum-java-binding-core/rust/src/proxy/transaction.rs
  exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
  exonum-java-binding-core/rust/src/storage/map_index.rs
  exonum-java-binding-core/rust/src/storage/proof_map_index.rs
  exonum-java-binding-core/rust/src/storage/value_set_index.rs
Labels: rust

#471 Migrate to Exonum 0.9.2 [ECR-1896]
  .travis.yml
  .travis/run_travis_job.sh
  CONTRIBUTING.md
  exonum-java-binding-core/pom.xml
  exonum-java-binding-core/rust/Cargo.lock
  exonum-java-binding-core/rust/Cargo.toml
  exonum-java-binding-core/rust/ejb-app/Cargo.toml
  exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
  exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
  exonum-java-binding-core/rust/integration_tests/Cargo.toml
  exonum-java-binding-core/rust/integration_tests/src/executor.rs
  exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
  exonum-java-binding-core/rust/integration_tests/src/test_service.rs
  exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
  exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
  exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
  exonum-java-binding-core/rust/src/lib.rs
  exonum-java-binding-core/rust/src/proxy/node.rs
  exonum-java-binding-core/rust/src/proxy/service.rs
  exonum-java-binding-core/rust/src/proxy/transaction.rs
  exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
  exonum-java-binding-core/rust/src/storage/map_index.rs
  exonum-java-binding-core/rust/src/storage/proof_map_index.rs
  exonum-java-binding-core/rust/src/storage/value_set_index.rs
  package_app.sh
  tests_profile
Labels: rust

#478 ECR-1950 Replace tree proof with flat proof in ProofMapIndexProxy
  CHANGELOG.md
  exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/CheckedFlatMapProof.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/MapEntry.java
  exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ProofMapIndexProxy.java
  exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcher.java
  exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcherTest.java
  exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapContainsMatcher.java
  exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapIndexProxyIntegrationTest.java
Labels: Next to merge :flight_arrival:

#482 Update TransactionProxy#execute to use transaction status from Java [ECR-1956]
  exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
  exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
  exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
  exonum-java-binding-core/rust/src/proxy/transaction.rs
  exonum-java-binding-core/rust/src/utils/errors.rs
  exonum-java-binding-core/rust/src/utils/mod.rs
  exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/NativeFacade.java
  exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/TestTxExecException.java
  exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/ThrowingTransactions.java
  exonum-java-binding-fakes/src/test/java/com/exonum/binding/fakes/mocks/ThrowingTransactionsTest.java
Labels: Next to merge :flight_arrival:

#503 Test hash code serializer using the likely 32-byte input
  exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/StandardSerializersRoundtripTest.java
Labels: Next to merge :flight_arrival:

#493 Add reflective serializer of any protobuf message [ECR-985]
  CHANGELOG.md
  exonum-java-binding-common/pom.xml
  exonum-java-binding-common/src/main/java/com/exonum/binding/common/serialization/ProtobufReflectiveSerializer.java
  exonum-java-binding-common/src/main/java/com/exonum/binding/common/serialization/StandardSerializers.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/ProtobufReflectiveSerializerTest.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/StandardSerializersRoundtripTest.java
  exonum-java-binding-common/src/test/proto/TestMessage.proto
  exonum-java-binding-cryptocurrency-demo/pom.xml
  exonum-java-binding-qa-service/pom.xml
  pom.xml
Labels: Next to merge :flight_arrival:

#494 Fix the DbKey#hashCode [ECR-2416]
  exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/DbKey.java
  exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyTest.java
Labels: Next to merge :flight_arrival:
