Repository exonum/exonum-java-binding, pull requests merged in 2019-03, with the labels that each got.

#750 Temporary switching back to Rust 1.32.0
  .travis.yml
  CONTRIBUTING.md
  exonum-java-binding/core/pom.xml
  exonum-java-binding/core/rust/ejb-app/TUTORIAL.md
  exonum-java-binding/core/rust/ejb-app/start_cryptocurrency_node.sh
  exonum-java-binding/core/rust/ejb-app/start_qa_node.sh
  exonum-java-binding/cryptocurrency-demo/Readme.md
  exonum-java-binding/tests_profile
Labels: experimental :balance_scale:

#737 Add time service support to QA service [ECR-2897]
  exonum-java-binding/core/src/main/java/com/exonum/binding/storage/database/Fork.java
  exonum-java-binding/core/src/main/java/com/exonum/binding/storage/database/Snapshot.java
  exonum-java-binding/core/src/main/java/com/exonum/binding/storage/database/View.java
  exonum-java-binding/qa-service/pom.xml
  exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
  exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java
  exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
  exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerIntegrationTest.java
  exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
  exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/TimeSchema.java
Labels: Next to merge :flight_arrival:

#764 Configuration of service in native code [ECR-2979]
  exonum-java-binding/core/rust/ejb-app/TUTORIAL.md
  exonum-java-binding/core/rust/ejb-app/start_cryptocurrency_node.sh
  exonum-java-binding/core/rust/ejb-app/start_qa_node.sh
  exonum-java-binding/core/rust/integration_tests/tests/service_runtime.rs
  exonum-java-binding/core/rust/src/runtime/cmd.rs
  exonum-java-binding/core/rust/src/runtime/config.rs
  exonum-java-binding/core/rust/src/runtime/java_service_runtime.rs
Labels: rust

#786 Sync multiple services with master
  .travis.yml
  exonum-java-binding/CHANGELOG.md
  exonum-java-binding/bom/pom.xml
  exonum-java-binding/common/pom.xml
  exonum-java-binding/core/pom.xml
  exonum-java-binding/core/rust/Cargo.lock
  exonum-java-binding/core/rust/Cargo.toml
  exonum-java-binding/core/rust/ejb-app/Cargo.toml
  exonum-java-binding/core/rust/integration_tests/Cargo.toml
  exonum-java-binding/core/rust/integration_tests/tests/service_proxy.rs
  exonum-java-binding/core/rust/integration_tests/tests/service_runtime.rs
  exonum-java-binding/core/rust/integration_tests/tests/transaction_proxy.rs
  exonum-java-binding/cryptocurrency-demo/pom.xml
  exonum-java-binding/fake-service/pom.xml
  exonum-java-binding/fakes/pom.xml
  exonum-java-binding/pom.xml
  exonum-java-binding/qa-service/pom.xml
  exonum-java-binding/service-archetype/pom.xml
  exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
  exonum-java-binding/testing/pom.xml
  exonum-java-binding/time-oracle/README.md
  exonum-java-binding/time-oracle/pom.xml
  exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchema.java
  exonum-java-binding/time-oracle/src/test/java/com/exonum/binding/time/UtcZonedDateTimeSerializerTest.java
  exonum-light-client/CHANGELOG.md
  exonum-light-client/pom.xml
Labels: do not merge ⛔️

#736 [ECR-2959] LC: Update health check json response format
  exonum-light-client/src/main/java/com/exonum/client/SystemApiHelper.java
  exonum-light-client/src/test/java/com/exonum/client/SystemApiHelperTest.java
Labels: do not merge ⛔️
